language: scala
scala:
  - 2.13.1
  - 2.12.10
  - 2.11.12
jdk:
  - openjdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION "set concurrentRestrictions in Global := Seq(Tags.limit(Tags.Test, 1))" clean coverage test
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
